env:
  RUBY_VERSION: 2.7.0
  PGHOST: 127.0.0.1
  PGUSER: postgres

name: Rails Quality Check
on: [push, pull_request]
jobs: 
  #Name of the Job/Task
  rubocop-linting:
    name: Rubocop
    # OS to run this workflow on
    runs-on: ubuntu-18.04
    steps:
      #Needed to checkout code from our repo
      - uses: actions/checkout@v2
      # Install Ruby
      - uses: actions/setup-ruby@v1
        with: 
          ruby-version: ${{ env.RUBY_VERSION}}
      - name: Install Rubocop for Rails
        run: gem install rubocop-rails
      - name: Check our code style
        run: rubocop
  #Name of the job/Task
  rspec-testing:
    #Name as it apears in the Action console
    name: RSpec Tests
    # Needs this job to pass before it runs
    needs: rubocop-linting
    runs-on: ubuntu-18.04
    # Config for Postgresql
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Setup Postgresql
        run: sudo apt-get -yqq install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create Database
        run: |
          RAILS_ENV=test
          bundler exec rails db:create
          bundler exec rails db:migrate
      - name: Run RSpec tests
        run: bin/rspec
